-- 코드를 입력하세요
SELECT B.AUTHOR_ID, C.AUTHOR_NAME, B.CATEGORY, SUM(SALES*PRICE) AS TOTAL_SALES
FROM BOOK_SALES A JOIN BOOK B ON A.BOOK_ID = B.BOOK_ID
                    JOIN AUTHOR C ON B.AUTHOR_ID = C.AUTHOR_ID
WHERE SALES_DATE LIKE "2022-01%"
GROUP BY B.AUTHOR_ID, AUTHOR_NAME, CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC