-- 코드를 작성해주세요
SELECT COUNT(*) AS COUNT 
FROM ECOLI_DATA
WHERE (GENOTYPE & 2) = 0 AND 
((GENOTYPE & 1) > 0 OR (GENOTYPE & 4) > 0)

# SELECT (GENOTYPE & 1), (GENOTYPE & 2), (GENOTYPE & 4), (GENOTYPE & 8)
# FROM ECOLI_DATA