-- 코드를 작성해주세요
# SELECT YM AS 'YEAR', 
#     ROUND(AVG(PM_VAL1), 2) AS 'PM10',
#     ROUND(AVG(PM_VAL2), 2) AS 'PM2.5' 
# FROM 
#     (SELECT DATE_FORMAT(YM, '%Y') AS YM, PM_VAL1, PM_VAL2
#     FROM AIR_POLLUTION 
#     WHERE LOCATION1 = "경기도" AND LOCATION2 = '수원') TB_AIR
# GROUP BY YEAR
# ORDER BY YEAR;

SELECT YEAR(YM) AS 'YEAR', 
    ROUND(AVG(PM_VAL1), 2) AS 'PM10',
    ROUND(AVG(PM_VAL2), 2) AS 'PM2.5' 
FROM AIR_POLLUTION
WHERE LOCATION2 = '수원'
GROUP BY YEAR
ORDER BY YEAR;