-- 코드를 입력하세요
SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM 
    (SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
    FROM ONLINE_SALE
    UNION
    SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
    FROM OFFLINE_SALE) TB
WHERE SALES_DATE >= "2022-03-01" AND SALES_DATE <= "2022-03-31"
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID
