# -- 코드를 입력하세요
SELECT TB_2.APNT_NO AS APNT_NO, TB_2.PT_NAME AS PT_NAME, 
 TB_2.PT_NO AS PT_NO, TB_2.MCDP_CD AS MCDP_CD, 
 D.DR_NAME, TB_2.APNT_YMD AS APNT_YMD
FROM DOCTOR D JOIN 
(SELECT TB_1.APNT_NO AS APNT_NO, A.PT_NAME AS PT_NAME, 
 TB_1.PT_NO AS PT_NO, TB_1.MCDP_CD AS MCDP_CD, 
 TB_1.MDDR_ID AS MDDR_ID, TB_1.APNT_YMD AS APNT_YMD
FROM PATIENT A JOIN 
(SELECT APNT_NO, PT_NO, MCDP_CD, MDDR_ID, APNT_YMD
FROM APPOINTMENT 
WHERE DATE_FORMAT(APNT_YMD, "%Y-%m-%d") = '2022-04-13' 
AND MCDP_CD = 'CS'
AND APNT_CNCL_YN = 'N'
) TB_1
ON A.PT_NO = TB_1.PT_NO) TB_2
ON D.DR_ID = TB_2.MDDR_ID
ORDER BY TB_2.APNT_YMD