-- 코드를 입력하세요
SELECT A.USER_ID, A.NICKNAME, SUM(B.PRICE) AS TOTAL_SALES
FROM USED_GOODS_USER A JOIN USED_GOODS_BOARD B
ON A.USER_ID = B.WRITER_ID
WHERE STATUS = "DONE"
GROUP BY B.WRITER_ID
HAVING SUM(B.PRICE) >= 700000
ORDER BY TOTAL_SALES

# SELECT WRITER_ID, SUM(PRICE)
# FROM USED_GOODS_BOARD
# WHERE STATUS = "DONE"
# GROUP BY WRITER_ID
# HAVING SUM(PRICE) >= 700000