# -- 코드를 입력하세요
# SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
# FROM MEMBER_PROFILE A JOIN REST_REVIEW B
# ON A.MEMBER_ID = B.MEMBER_ID
# GROUP BY B.MEMBER_ID

SELECT A.MEMBER_NAME, B.REVIEW_TEXT, DATE_FORMAT(B.REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM MEMBER_PROFILE A JOIN REST_REVIEW B
ON A.MEMBER_ID = B.MEMBER_ID
WHERE A.MEMBER_ID IN (SELECT MEMBER_ID
FROM REST_REVIEW
GROUP BY MEMBER_ID
HAVING COUNT(MEMBER_ID) = (SELECT COUNT(*) AS SCORE
FROM REST_REVIEW 
GROUP BY MEMBER_ID
ORDER BY SCORE DESC
LIMIT 1))
ORDER BY REVIEW_DATE, REVIEW_TEXT

