-- 코드를 입력하세요
# SELECT CATEGORY, COUNT(CATEGORY) AS PRODUCTS
# FROM (SELECT PRODUCT_ID, SUBSTRING(PRODUCT_CODE, 1, 2) AS CATEGORY, PRICE
# FROM PRODUCT) AS B
# GROUP BY CATEGORY;

SELECT SUBSTRING(PRODUCT_CODE, 1, 2) AS CATEGORY, COUNT(PRODUCT_ID)
FROM PRODUCT
GROUP BY SUBSTRING(PRODUCT_CODE, 1, 2)
ORDER BY CATEGORY;