-- 코드를 입력하세요
SELECT TB.FLAVOR
FROM ICECREAM_INFO ICE JOIN
    (SELECT FLAVOR
     FROM FIRST_HALF
     WHERE TOTAL_ORDER >= 3000) TB
     ON ICE.FLAVOR = TB.FLAVOR
WHERE ICE.INGREDIENT_TYPE = "fruit_based";