-- 코드를 입력하세요
SELECT DISTINCT A.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
ON A.CAR_ID = B.CAR_ID
WHERE DATE_FORMAT(B.START_DATE, "%Y-%m") = "2022-10" AND A.CAR_TYPE = "세단"
ORDER BY CAR_ID DESC