SELECT TB.SCORE, A.EMP_NO, A.EMP_NAME, A.POSITION, A.EMAIL
FROM HR_EMPLOYEES A JOIN (SELECT EMP_NO, SUM(SCORE) AS SCORE
FROM HR_GRADE 
GROUP BY EMP_NO
ORDER BY SCORE DESC
LIMIT 1) TB
ON A.EMP_NO = TB.EMP_NO

